Repository aave/interface, pull requests merged in 2022-12, with the labels that each got.

#1297 fix: paraswap route blacklist
  src/components/transactions/Repay/CollateralRepayActions.tsx
  src/components/transactions/Repay/CollateralRepayModalContent.tsx
  src/components/transactions/Swap/SwapActions.tsx
  src/components/transactions/Swap/SwapModalContent.tsx
  src/components/transactions/TxActionsWrapper.tsx
  src/helpers/useParaSwapTransactionHandler.tsx
  src/hooks/paraswap/common.ts
  src/hooks/paraswap/useCollateralRepaySwap.tsx
  src/hooks/paraswap/useCollateralSwap.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/SlippageList.tsx
  src/store/poolSlice.ts
Labels: QC Failed

#1342 feat: show frozen reserves list for markets page
  cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/bal.polygon-v2.cy.ts
  pages/markets.page.tsx
  src/components/ReserveSubheader.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/markets/MarketAssetsList.tsx
  src/modules/markets/MarketAssetsListContainer.tsx
  src/modules/markets/MarketAssetsListItem.tsx
  src/modules/markets/MarketAssetsListMobileItem.tsx
Labels: QC Passed, Ready for Dev Review

#1345 fix: duplicated warning icons if asset is frozen and has borrow disabled flag
  src/components/infoTooltips/FrozenTooltip.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListMobileItem.tsx
  src/modules/dashboard/lists/ListItemWrapper.tsx
  src/modules/dashboard/lists/ListMobileItemWrapper.tsx
  src/utils/marketsAndNetworksConfig.ts
Labels: QC Passed

#1349 feat: support dynamic balance text for asset input
  src/components/transactions/AssetInput.tsx
  src/components/transactions/Borrow/BorrowModalContent.tsx
  src/components/transactions/Repay/CollateralRepayModalContent.tsx
  src/components/transactions/Repay/RepayModalContent.tsx
  src/components/transactions/Stake/StakeModalContent.tsx
  src/components/transactions/Supply/SupplyModalContent.tsx
  src/components/transactions/Swap/SwapModalContent.tsx
  src/components/transactions/UnStake/UnStakeModalContent.tsx
  src/components/transactions/Withdraw/WithdrawModalContent.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
Labels: QC Passed, Ready for Dev Review

#1348 chore: screening optimisations
  cypress/e2e/2-settings/wallet-connect.cy.ts
  src/components/AddressBlocked.tsx
  src/libs/web3-data-provider/Web3Provider.tsx
Labels: QC Passed

#1325 chore: permit modifications
  cypress/e2e/1-v3-markets/3-polygon-v3-market/e-mode.polygon-v3.cy.ts
  package.json
  src/components/TextWithTooltip.tsx
  src/components/infoModalContents/ApprovalInfoContent.tsx
  src/components/infoModalContents/RetryWithApprovalInfoContent.tsx
  src/components/infoTooltips/ApprovalTooltip.tsx
  src/components/transactions/Borrow/BorrowActions.tsx
  src/components/transactions/FlowCommons/ApprovalMethodToggleButton.tsx
  src/components/transactions/FlowCommons/LeftHelperText.tsx
  src/components/transactions/FlowCommons/RightHelperText.tsx
  src/components/transactions/Repay/CollateralRepayActions.tsx
  src/components/transactions/Repay/RepayActions.tsx
  src/components/transactions/Stake/StakeActions.tsx
  src/components/transactions/Supply/SupplyActions.tsx
  src/components/transactions/Swap/SwapActions.tsx
  src/components/transactions/TxActionsWrapper.tsx
  src/components/transactions/Withdraw/WithdrawActions.tsx
  src/helpers/useTransactionHandler.tsx
  src/hooks/useModal.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/store/poolSlice.ts
  src/store/protocolDataSlice.ts
  src/store/walletSlice.ts
  src/ui-config/permitConfig.ts
  yarn.lock
Labels: QC Passed, Ready for Dev Review

#1219 feat: paraswap feature updates
  cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/dai.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/ren.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/tusd.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/usdc.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/usdt.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/usdc.polygon-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/usdt.polygon-v2.cy.ts
  cypress/e2e/0-v2-markets/3-avalanche-v2-market/0-assets/usdc.avalanche-v2.cy.ts
  cypress/e2e/0-v2-markets/3-avalanche-v2-market/0-assets/usdt.avalanche-v2.cy.ts
  cypress/e2e/1-v3-markets/1-arbitrum-v3-market/0-assets/usdc.arbitrum-v3.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/0-assets/usdc.avalanche-v3.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/0-assets/usdt.avalacnhe-v3.cy.ts
  cypress/e2e/1-v3-markets/3-polygon-v3-market/0-assets/usdc.polygon-v3.cy.ts
  cypress/e2e/1-v3-markets/3-polygon-v3-market/0-assets/usdt.polygon-v3.cy.ts
  cypress/e2e/1-v3-markets/4-optimism-v3-market/0-assets/usdc.optimism-v3.cy.ts
  cypress/e2e/1-v3-markets/4-optimism-v3-market/0-assets/usdt.optimism-v3.cy.ts
  cypress/e2e/1-v3-markets/5-fantom-v3-market/0-assets/usdc.fantom-v3.cy.ts
  cypress/fixtures/assets.json
  cypress/support/steps/main.steps.ts
  package.json
  public/icons/other/paraswap.svg
  src/components/infoTooltips/PriceImpactTooltip.tsx
  src/components/infoTooltips/SlippageTooltip.tsx
  src/components/transactions/AssetInput.tsx
  src/components/transactions/Borrow/BorrowModalContent.tsx
  src/components/transactions/FlowCommons/TxModalDetails.tsx
  src/components/transactions/Repay/CollateralRepayActions.tsx
  src/components/transactions/Repay/CollateralRepayModalContent.tsx
  src/components/transactions/Repay/RepayModal.tsx
  src/components/transactions/Repay/RepayModalContent.tsx
  src/components/transactions/Repay/RepayTypeSelector.tsx
  src/components/transactions/Swap/SwapActions.tsx
  src/components/transactions/Swap/SwapModalContent.tsx
  src/components/transactions/Swap/SwapModalDetails.tsx
  src/components/transactions/TxActionsWrapper.tsx
  src/helpers/useParaSwapTransactionHandler.tsx
  src/hooks/paraswap/common.ts
  src/hooks/paraswap/useCollateralRepaySwap.tsx
  src/hooks/paraswap/useCollateralSwap.tsx
  src/hooks/useModal.tsx
  src/hooks/useSwap.ts
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/locales/es/messages.po
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListItem.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListMobileItem.tsx
  src/modules/dashboard/lists/SlippageList.tsx
  src/static-build/proposals.json
  src/store/poolSlice.ts
  yarn.lock
Labels: QC Passed, Ready for Dev Review

#1364 chore: replace rotationDelay with check on max retries
  src/utils/__tests__/RotationProvider.test.ts
  src/utils/rotationProvider.ts
Labels: QC Passed

#1367 feat: festive aave
  public/aave_santa.svg
  src/layouts/AppHeader.tsx
  src/uiConfig.ts
Labels: Ready for Dev Review

#1374 fix: show collateral as disabled if it is disabled on the reserve
  src/components/transactions/Supply/SupplyModalContent.tsx
Labels: QC Passed, Ready for Dev Review

#1378 fix: don't clear account in connect wallet callback
  cypress/e2e/1-v3-markets/3-polygon-v3-market/e-mode.polygon-v3.cy.ts
  cypress/e2e/2-settings/wallet-connect.cy.ts
  src/components/AddressBlocked.tsx
  src/libs/web3-data-provider/Web3Provider.tsx
  src/modules/reserve-overview/ReserveActions.tsx
Labels: QC Passed, Ready for Dev Review

#1366 chore: add translation watchmode address
  src/components/WalletConnection/WalletSelector.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
Labels: QC Passed, Ready for Dev Review

#1369 feat: redesign of 'Your info' section on reserve overview page
  pages/reserve-overview.page.tsx
  public/icons/wallets/walletIcon.svg
  public/icons/wallets/walletIconHover.svg
  src/components/icons/WalletIcon.tsx
  src/components/transactions/FlowCommons/Success.tsx
  src/components/transactions/Warnings/BorrowCapWarning.tsx
  src/components/transactions/Warnings/DebtCeilingWarning.tsx
  src/components/transactions/Warnings/SupplyCapWarning.tsx
  src/hooks/useAssetCaps.tsx
  src/hooks/useReserveActionState.tsx
  src/locales/en/messages.po
  src/modules/dashboard/lists/SupplyAssetsList/WalletEmptyInfo.tsx
  src/modules/reserve-overview/AddTokenDropdown.tsx
  src/modules/reserve-overview/ReserveActions.tsx
Labels: QC Passed, Ready for Dev Review

#1391 fix: remove borrow button when borrowing is disabled for asset on overview page
  src/modules/reserve-overview/ReserveActions.tsx
Labels: QC Passed, Ready for Dev Review
