Repository aave/interface, pull requests merged in 2022-09, with the labels that each got.

#1089 feat: eth borrow disable
  src/components/ContentWithTooltip.tsx
  src/components/lists/ListMobileItem.tsx
  src/components/transactions/Warnings/ETHBorrowWarning.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListItem.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListMobileItem.tsx
  src/modules/dashboard/lists/ListItemWrapper.tsx
  src/modules/dashboard/lists/ListMobileItemWrapper.tsx
  src/modules/markets/AssetsListItem.tsx
  src/modules/markets/AssetsListMobileItem.tsx
  src/modules/reserve-overview/ReserveConfiguration.tsx
Labels: QC Passed, Ready for QA

#1098 fix: show borrow info for assets with active borrows
  src/modules/markets/AssetsListItem.tsx
  src/modules/reserve-overview/ReserveConfiguration.tsx
Labels: QC Passed

#1103 fix: only show stable borrow rate if borrowing is enabled
  cypress/e2e/0-v2-markets/0-main-v2-market/critical-conditions.aave-v2.cy.ts
  src/modules/markets/AssetsListItem.tsx
Labels: QC Passed

#1112 chore: update debt ceiling tooltip text
  src/components/caps/DebtCeilingStatus.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
Labels: QC Passed

#1116 chore: run prettier on cypress files
  cypress.config.ts
  cypress/README.md
  cypress/configs/settings.config.ts
  cypress/configs/v2-markets/amm-v2-full.config.ts
  cypress/configs/v2-markets/amm-v2-smoke.config.ts
  cypress/configs/v2-markets/avalanche-v2-full.config.ts
  cypress/configs/v2-markets/ethereum-v2-additional.config.ts
  cypress/configs/v2-markets/ethereum-v2-full.config.ts
  cypress/configs/v2-markets/ethereum-v2-smoke.config.ts
  cypress/configs/v2-markets/polygon-v2-additional.config.ts
  cypress/configs/v2-markets/polygon-v2-full.config.ts
  cypress/configs/v2-markets/polygon-v2-smoke.config.ts
  cypress/configs/v3-markets/arbitrum-v3-additional.config.ts
  cypress/configs/v3-markets/arbitrum-v3-full.config.ts
  cypress/configs/v3-markets/arbitrum-v3-smoke.config.ts
  cypress/configs/v3-markets/avalanche-v3-additional.config.ts
  cypress/configs/v3-markets/avalanche-v3-full.config.ts
  cypress/configs/v3-markets/avalanche-v3-smoke.config.ts
  cypress/configs/v3-markets/fantom-v3-additional.config.ts
  cypress/configs/v3-markets/fantom-v3-full.config.ts
  cypress/configs/v3-markets/fantom-v3-smoke.config.ts
  cypress/configs/v3-markets/optimism-v3-additional.config.ts
  cypress/configs/v3-markets/optimism-v3-full.config.ts
  cypress/configs/v3-markets/optimism-v3-smoke.config.ts
  cypress/configs/v3-markets/polygon-v3-additional.config.ts
  cypress/configs/v3-markets/polygon-v3-full.config.ts
  cypress/configs/v3-markets/polygon-v3-smoke.config.ts
  cypress/fixtures/constans.json
Labels: QC Passed

#1115 feat: switch governance gateway to cloudflare
  src/ui-config/governanceConfig.ts
Labels: QC Passed

#1131 e2e - refactor
  cypress/e2e/0-v2-markets/0-main-v2-market/stake.aave-v2.cy.ts
  cypress/e2e/1-v3-markets/3-polygon-v3-market/e-mode.polygon-v3.cy.ts
  cypress/e2e/1-v3-markets/3-polygon-v3-market/isolated-and-emode.polygon-v3.cy.ts
  cypress/support/commands.ts
  cypress/support/cypress.d.ts
  cypress/support/e2e.ts
  cypress/support/steps/actions.steps.ts
  cypress/support/steps/main.steps.ts
  cypress/support/steps/verification.steps.ts
  package.json
  tsconfig.json
  yarn.lock
Labels: Ready for QA

#1141 feat: refactor frozen warnings
  .github/workflows/build-test-deploy.yml
  .github/workflows/test-deploy-fork.yml
  src/components/infoTooltips/FrozenTooltip.tsx
  src/components/infoTooltips/FrozenWarning.tsx
  src/components/transactions/Supply/SupplyModalContent.tsx
  src/components/transactions/Warnings/HarmonyWarning.tsx
  src/components/transactions/Warnings/MarketWarning.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsList.tsx
  src/modules/dashboard/lists/ListItemWrapper.tsx
  src/modules/dashboard/lists/ListMobileItemWrapper.tsx
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsList.tsx
  src/modules/markets/AssetsList.tsx
  src/modules/reserve-overview/ReserveActions.tsx
  src/modules/reserve-overview/ReserveConfiguration.tsx
  src/utils/marketsAndNetworksConfig.ts
Labels: QC Passed

#1113 feat: removed warnings related to eth borrow being disabled
  .prettierignore
  cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/eth.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/1-amm-v2-market/0-assets/eth.amm-v2.cy.ts
  src/components/lists/ListMobileItem.tsx
  src/components/transactions/Warnings/ETHBorrowWarning.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListItem.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListMobileItem.tsx
  src/modules/dashboard/lists/ListItemWrapper.tsx
  src/modules/dashboard/lists/ListMobileItemWrapper.tsx
  src/modules/markets/AssetsListItem.tsx
  src/modules/markets/AssetsListMobileItem.tsx
  src/modules/reserve-overview/ReserveConfiguration.tsx
Labels: QC Passed

#1094 feat: add custom error page templates
  .prettierignore
  pages/404.page.tsx
  pages/500.page.tsx
  pages/_error.page.tsx
  public/404/404DarkMode.svg
  public/404/404LightMode.svg
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/static-build/proposals.json
Labels: QC Passed

#999 feat: warn about governance in borrow modal
  src/components/transactions/Borrow/BorrowModalContent.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
Labels: QC Passed

#1152 fix: btc.b symbol
  src/ui-config/reservePatches.ts
Labels: QC Passed

#1102 feat: graph improvements
  .eslintignore
  package.json
  pages/index.page.tsx
  pages/reserve-overview.page.tsx
  pages/staking.staking.tsx
  src/components/MarketSwitcher.tsx
  src/components/StyledToggleButton.tsx
  src/components/StyledToggleButtonGroup.tsx
  src/components/caps/CapsCircularStatus.tsx
  src/components/transactions/Borrow/BorrowModalContent.tsx
  src/components/transactions/Repay/CollateralRepayModalContent.tsx
  src/components/transactions/Repay/RepayTypeSelector.tsx
  src/components/transactions/Swap/SwapModalContent.tsx
  src/hooks/useReservesHistory.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/reserve-overview/ReserveConfiguration.tsx
  src/modules/reserve-overview/ReservePanels.tsx
  src/modules/reserve-overview/graphs/ApyGraph.tsx
  src/modules/reserve-overview/graphs/ApyGraphContainer.tsx
  src/modules/reserve-overview/graphs/GraphLegend.tsx
  src/modules/reserve-overview/graphs/GraphTimeRangeSelector.tsx
  src/modules/reserve-overview/graphs/InterestRateModelGraph.tsx
  src/modules/reserve-overview/graphs/InterestRateModelGraphContainer.tsx
  src/utils/theme.tsx
  yarn.lock
Labels: QC Passed

#1175 chore: add QA verification checklist item for reviews
  .github/pull_request_template.md
Labels: QC Passed

#1173 fix: remove duplicate debt ceiling warning
  src/components/transactions/Borrow/BorrowModalContent.tsx
Labels: QC Passed

#1181 fix(swap-modal): open swap modal on mobile
  src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListMobileItem.tsx
Labels: QC Passed

#1168 fix: correct bridge message
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsList.tsx
  src/modules/dashboard/lists/SupplyAssetsList/WalletEmptyInfo.tsx
  src/modules/reserve-overview/ReserveActions.tsx
Labels: QC Passed

#1171 fix: debt ceiling wording
  src/components/caps/DebtCeilingStatus.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/reserve-overview/ReserveConfiguration.tsx
Labels: QC Passed

#1174 feat: market search
  src/components/lists/ListWrapper.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsList.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsList.tsx
  src/modules/dashboard/lists/ListLoader.tsx
  src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsList.tsx
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsList.tsx
  src/modules/faucet/FaucetAssetsList.tsx
  src/modules/markets/AssetListTitle.tsx
  src/modules/markets/AssetSearchInput.tsx
  src/modules/markets/AssetsList.tsx
Labels: QC Passed

#1185 fix: lint
  src/static-build/ipfs.ts
Labels: QC Passed

#1184 chore: update 404 image
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/e-mode.avalanche-v3.cy.ts
  pages/404.page.tsx
  public/404/404.svg
  public/404/404DarkMode.svg
  public/404/404LightMode.svg
Labels: QC Passed

#1178 feat: add watch mode only wallet address
  cypress/e2e/2-settings/wallet-connect.cy.ts
  cypress/support/steps/configuration.steps.ts
  src/components/WalletConnection/WalletSelector.tsx
  src/components/infoTooltips/WatchOnlyModeTooltip.tsx
  src/components/transactions/ClaimRewards/ClaimRewardsModalContent.tsx
  src/components/transactions/Emode/EmodeModalContent.tsx
  src/components/transactions/FlowCommons/ModalWrapper.tsx
  src/components/transactions/GovDelegation/GovDelegationModalContent.tsx
  src/components/transactions/GovVote/GovVoteModalContent.tsx
  src/components/transactions/Stake/StakeModalContent.tsx
  src/components/transactions/StakeCooldown/StakeCooldownModalContent.tsx
  src/components/transactions/StakeRewardClaim/StakeRewardClaimModalContent.tsx
  src/components/transactions/TxActionsWrapper.tsx
  src/components/transactions/UnStake/UnStakeModalContent.tsx
  src/hooks/useWalletModal.tsx
  src/layouts/AppHeader.tsx
  src/layouts/WalletWidget.tsx
  src/layouts/components/DrawerWrapper.tsx
  src/libs/web3-data-provider/Web3Provider.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
Labels: QC Passed
