Repository aave/interface, pull requests merged in 2022-08, with the labels that each got.

#987 chore: add in commitlint
  .husky/commit-msg
  commitlint.config.js
  package.json
  yarn.lock
Labels: QC Passed

#993 fix: dashboard states
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsList.tsx
  src/modules/reserve-overview/ReserveConfiguration.tsx
  src/utils/marketsAndNetworksConfig.ts
Labels: QC Passed

#962 fix: governance cache failure
  src/static-build/populateCache.ts
Labels: QC Passed

#1003 Fix/950 phantom rewards
  src/ui-config/networksConfig.ts
  src/utils/marketsAndNetworksConfig.ts
Labels: QC Passed

#1010 feat(client): add info on how to exit isolation mode
  src/components/transactions/CollateralChange/CollateralChangeModalContent.tsx
  src/components/transactions/Supply/SupplyModalContent.tsx
  src/components/transactions/Warnings/IsolationModeWarning.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
Labels: QC Passed

#1015 feat: add mai icon and name
  public/icons/tokens/mai.svg
  src/ui-config/reservePatches.ts
Labels: QC Passed

#1013 improve critical conditions test
  cypress/configs/v2-markets/amm-v2-full.config.json
  cypress/configs/v2-markets/avalanche-v2-additional.config.json
  cypress/configs/v2-markets/avalanche-v2-full.config.json
  cypress/configs/v2-markets/ethereum-v2-additional.config.json
  cypress/configs/v2-markets/polygon-v2-additional.config.json
  cypress/configs/v2-markets/polygon-v2-full.config.json
  cypress/configs/v3-markets/arbitrum-v3-additional.config.json
  cypress/configs/v3-markets/avalanche-v3-additional.config.json
  cypress/configs/v3-markets/avalanche-v3-full.config.json
  cypress/configs/v3-markets/fantom-v3-additional.config.json
  cypress/configs/v3-markets/fantom-v3-full.config.json
  cypress/configs/v3-markets/optimism-v3-additional.config.json
  cypress/configs/v3-markets/polygon-v3-additional.config.json
  cypress/configs/v3-markets/polygon-v3-full.config.json
  cypress/integration/0-v2-markets/0-main-v2-market/critical-conditions.aave-v2.spec.ts
  cypress/integration/0-v2-markets/1-amm-v2-market/critical-conditions.amm-v2.spec.ts
  cypress/integration/0-v2-markets/2-polygon-v2-market/critical-conditions.polygon-v2.spec.ts
  cypress/integration/0-v2-markets/3-avalanche-v2-market/critical-conditions.avalanche-v2.spec.ts
  cypress/integration/1-v3-markets/2-avalanche-v3-market/critical-conditions.avalanche-v3.spec.ts
  cypress/integration/1-v3-markets/3-polygon-v3-market/critical-conditions.polygon-v3.spec.ts
  cypress/integration/1-v3-markets/4-optimism-v3-market/0-assets/susd.optimism-v3.spec.ts
  cypress/integration/1-v3-markets/4-optimism-v3-market/critical-conditions.optimism-v3.spec.ts
  cypress/integration/1-v3-markets/5-fantom-v3-market/critical-conditions.fantom-v3.spec.ts
  cypress/support/steps/main.steps.ts
  cypress/support/steps/verification.steps.ts
Labels: QC Passed, tests

#1017 feat: address screening
  .env.development
  .env.example
  .github/actions/build/action.yml
  custom.d.ts
  pages/_app.page.tsx
  src/components/AddressBlocked.tsx
  src/components/AddressBlockedModal.tsx
  src/hooks/useAddressAllowed.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
Labels: QC Passed

#998 e2e test for details page
  cypress/integration/2-settings/details.page.aave-v2.spec.ts
  cypress/integration/2-settings/wallet-connect.spec.ts
  cypress/support/steps/actions.steps.ts
  src/modules/markets/AssetsListItem.tsx
  src/modules/reserve-overview/ReserveActions.tsx
Labels: tests

#1016 fix: ordering and available amounts in repay modal
  src/components/transactions/Repay/RepayModalContent.tsx
Labels: QC Passed

#953 feat: improve emode menu ux
  cypress/integration/1-v3-markets/2-avalanche-v3-market/e-mode.avalanche-v3.spec.ts
  cypress/support/steps/main.steps.ts
  public/icons/tokens/mai.svg
  src/components/transactions/Emode/EmodeActions.tsx
  src/components/transactions/Emode/EmodeModal.tsx
  src/components/transactions/Emode/EmodeModalContent.tsx
  src/components/transactions/Emode/EmodeSelect.tsx
  src/hooks/useModal.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/DashboardEModeButton.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsList.tsx
  src/utils/theme.tsx
Labels: QC Passed

#1036 fix: update bridge and faucet button styles
  src/components/BridgeButton.tsx
  src/components/FaucetButton.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/DashboardListTopPanel.tsx
Labels: QC Passed

#1037 chore: replace optimism public fallback rpc
  src/ui-config/networksConfig.ts
Labels: QC Passed

#1055 ci: update third-party actions
  .github/actions/analyze-comment/action.yml
  .github/actions/build/action.yml
  .github/actions/cypress/action.yml
  .github/workflows/build-fork.yml
  .github/workflows/build-test-deploy.yml
  .github/workflows/crowdin-download.yml
  .github/workflows/crowdin-upload.yml
  .github/workflows/i18n-check.yml
  .github/workflows/test-deploy-fork.yml
  .github/workflows/update-cache.yml
  .github/workflows/update-prod-staging.yml
Labels: QC Passed

#1070 fix: liquidation risk colors
  src/modules/dashboard/LiquidationRiskParametresModal/LiquidationRiskParametresModal.tsx
  src/modules/dashboard/LiquidationRiskParametresModal/components/InfoWrapper.tsx
  src/modules/dashboard/LiquidationRiskParametresModal/components/LTVContent.tsx
Labels: QC Passed

#1004 chore: testnet and ui helper contract updates
  cypress/fixtures/markets.json
  package.json
  src/hooks/app-data-provider/graphql/hooks.tsx
  src/ui-config/marketsConfig.tsx
  src/ui-config/networksConfig.ts
  src/ui-config/permitConfig.ts
  yarn.lock
Labels: QC Passed
