Repository aave/interface, pull requests merged in 2022-10, with the labels that each got.

#1186 fix: use gateway retry logic anywhere we fetch ipfs data
  pages/governance/ipfs-preview.governance.tsx
  pages/governance/proposal/index.governance.tsx
  src/modules/governance/ProposalsList.tsx
  src/modules/governance/utils/getProposalMetadata.ts
  src/ui-config/governanceConfig.ts
Labels: QC Passed

#1192 chore: bump packages
  package.json
  scripts/populate-cache.js
  src/modules/reserve-overview/ReserveConfiguration.tsx
  src/static-build/ipfs.ts
  yarn.lock
Labels: QC Passed

#1204 chore: add dependency scanning for PRs
  .github/dependabot.yml
  .github/workflows/dependency-review.yml
Labels: Ready for Dev Review

#1205 chore: update alert instances to warning primitive component
  cypress/e2e/2-settings/stake-abpt.cy.ts
  src/components/WalletConnection/WalletSelector.tsx
  src/components/primitives/Warning.tsx
  src/components/transactions/Borrow/BorrowModalContent.tsx
  src/components/transactions/CollateralChange/CollateralChangeModalContent.tsx
  src/components/transactions/FlowCommons/GasEstimationError.tsx
  src/components/transactions/RateSwitch/RateSwitchModalContent.tsx
  src/components/transactions/StakeCooldown/StakeCooldownModalContent.tsx
  src/components/transactions/Warnings/IsolationModeWarning.tsx
  src/components/transactions/Withdraw/WithdrawModalContent.tsx
  src/layouts/WalletWidget.tsx
  src/modules/governance/proposal/VoteInfo.tsx
Labels: QC Passed

#1215 fix: made connecting with watch mode on page load more reliable
  package.json
  src/components/WalletConnection/WalletSelector.tsx
  src/layouts/WalletWidget.tsx
  src/libs/web3-data-provider/WalletOptions.ts
  src/libs/web3-data-provider/Web3Provider.tsx
Labels: QC Passed

#973 feat: transak on-ramp integration
  .env.example
  .github/actions/build/action.yml
  pages/staking.staking.tsx
  public/icons/onRampServices/transak.svg
  src/hooks/useCryptoBuyAvailable.tsx
  src/layouts/MoreMenu.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/reserve-overview/ReserveActions.tsx
  src/modules/staking/BuyWithFiat.tsx
  src/modules/staking/BuyWithFiatModal.tsx
  src/modules/staking/GetABPToken.tsx
  src/modules/staking/GetABPTokenModal.tsx
  src/ui-config/menu-items/index.tsx
  src/ui-config/onRampServicesConfig.tsx
Labels: QC Passed

#1221 chore: add stETH rewards message
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/reserve-overview/ReserveConfiguration.tsx
Labels: Ready for Dev Review

#1187 chore: add staking apr when no wallet connected
  pages/staking.staking.tsx
  src/components/ConnectWalletPaperStaking.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/governance/GovernanceTopPanel.tsx
  src/modules/staking/StakingHeader.tsx
  src/modules/staking/StakingPanel.tsx
  src/modules/staking/StakingPanelNoWallet.tsx
Labels: QC Passed

#1220 chore: add aip end date
  pages/governance/proposal/[proposalId].governance.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
Labels: Ready for Dev Review

#1108 Add label with fork pr pipeline result
  .github/actions/fork-result-label/action.yml
  .github/workflows/test-deploy-fork.yml
Labels: QC Passed

#1240 ci: make pin failures more visible
  .github/actions/private-ipfs-pin/action.yml
  .github/workflows/update-prod-staging.yml
Labels: Ready for Dev Review

#1241 fix: graph initial load error
  .github/actions/fork-result-label/action.yml
  src/hooks/useReservesHistory.tsx
Labels: QC Passed

#1245 fix: amm market incentives display
  src/components/transactions/ClaimRewards/ClaimRewardsModalContent.tsx
  src/modules/dashboard/DashboardTopPanel.tsx
Labels: QC Passed

#1258 fix: unstake text
  src/components/transactions/UnStake/UnStakeModalContent.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
Labels: QC Passed

#1259 fix: disable charts for broken assets
  src/hooks/useReservesHistory.tsx
  src/modules/reserve-overview/ReserveConfiguration.tsx
Labels: QC Passed

#1262 fix: update pinata action
  .github/workflows/build-test-deploy.yml
  .github/workflows/test-deploy-fork.yml
  .github/workflows/update-prod-staging.yml
Labels: Ready for Dev Review

#1265 feat: round down formatting
  pages/governance/proposal/[proposalId].governance.tsx
  src/components/primitives/FormattedNumber.tsx
  src/modules/governance/VoteBar.tsx
  src/modules/governance/proposal/VotersListItem.tsx
Labels: Ready for Dev Review

#1261 fix: CBW wallet selector naming
  src/components/WalletConnection/WalletSelector.tsx
Labels: CI Passed

#1244 feat: add in governance voters to proposal UI
  .env.development
  .env.example
  .github/actions/build/action.yml
  .prettierignore
  custom.d.ts
  package.json
  pages/governance/proposal/[proposalId].governance.tsx
  src/components/primitives/FormattedNumber.tsx
  src/hooks/app-data-provider/usePoolDataRPC.tsx
  src/hooks/useAddressAllowed.tsx
  src/hooks/usePreviousState.ts
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/governance/VoteBar.tsx
  src/modules/governance/proposal/VotersList.tsx
  src/modules/governance/proposal/VotersListContainer.tsx
  src/modules/governance/proposal/VotersListItem.tsx
  src/modules/governance/proposal/VotersListModal.tsx
  src/modules/governance/utils/formatProposal.ts
  src/modules/staking/BuyWithFiatModal.tsx
  yarn.lock
Labels: QC Passed

#1136 feat: custom fallback revised
  cypress/tsconfig.json
  src/components/__tests__/example.test.ts
  src/utils/__tests__/RotationProvider.test.ts
  src/utils/__tests__/marketsAndNetworkConfig.spec.ts
  src/utils/marketsAndNetworksConfig.ts
  src/utils/rotationProvider.ts
  tsconfig.json
Labels: QC Passed, Ready for Dev Review

#1291 chore: add additional public rpcs to all networks
  cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/ghst.polygon-v2.cy.ts
  cypress/e2e/1-v3-markets/4-optimism-v3-market/0-assets/usdt.optimism-v3.cy.ts
  cypress/e2e/1-v3-markets/4-optimism-v3-market/e-mode.optimism-v3.cy.ts
  src/ui-config/networksConfig.ts
Labels: QC Passed
