Repository aave/interface, pull requests merged in 2022-11, with the labels that each got.

#1288 chore: ampl warning message and governance page text fix
  src/components/Warnings/AMPLWarning.tsx
  src/components/infoTooltips/AMPLToolTip.tsx
  src/components/infoTooltips/AMPLWarning.tsx
  src/components/transactions/Supply/SupplyModalContent.tsx
  src/components/transactions/Warnings/AMPLWarning.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/ListItemWrapper.tsx
  src/modules/dashboard/lists/ListMobileItemWrapper.tsx
  src/modules/governance/proposal/ProposalTopPanel.tsx
  src/modules/markets/AssetsListItem.tsx
  src/modules/reserve-overview/ReserveConfiguration.tsx
Labels: Ready for QA Review

#1299 chore: specify lint directories
  package.json
Labels: Ready for Dev Review

#1301 fix: use next router for pushing route
  src/store/utils/queryParams.ts
Labels: Ready for QA Review, CI Passed

#1296 chore: disable borrow warning
  src/components/infoTooltips/FrozenTooltip.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/reserve-overview/BorrowInfo.tsx
  src/modules/reserve-overview/ReserveConfiguration.tsx
  src/modules/reserve-overview/SupplyInfo.tsx
  src/utils/marketsAndNetworksConfig.ts
Labels: QC Passed, Ready for QA Review

#1302 fix: maintain query parameters
  package.json
  src/hooks/useAssetCaps.tsx
  src/store/protocolDataSlice.ts
  src/store/root.ts
  src/store/utils/queryParams.ts
  yarn.lock
Labels: CI Passed

#1310 e2e for mobile resolution on the Governance page
  .github/workflows/build-test-deploy.yml
  .github/workflows/test-deploy-fork.yml
  cypress/configs/mobile.config.ts
  cypress/configs/settings.config.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/swap.aave-v2.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/e-mode.avalanche-v3.cy.ts
  cypress/e2e/2-settings/mobile.cy.ts
  pages/governance/proposal/[proposalId].governance.tsx
  src/layouts/MobileMenu.tsx
  src/layouts/components/DrawerWrapper.tsx
Labels: Ready for Dev Review

#1327 chore: prefix market components with 'Market'
  pages/markets.page.tsx
  src/locales/en/messages.po
  src/modules/markets/MarketAssetListTitle.tsx
  src/modules/markets/MarketAssetSearchInput.tsx
  src/modules/markets/MarketAssetsList.tsx
  src/modules/markets/MarketAssetsListItem.tsx
  src/modules/markets/MarketAssetsListItemLoader.tsx
  src/modules/markets/MarketAssetsListMobileItem.tsx
  src/modules/markets/MarketAssetsListMobileItemLoader.tsx
Labels: Ready for QA Review

#1329 chore: added gitpoap message
  README.md
Labels: Ready for Dev Review

#1328 chore: update contributing guidelines
  CONTRIBUTING.md
Labels: Ready for Dev Review

#1330 fix: governance images
  pages/governance/proposal/[proposalId].governance.tsx
Labels: CI Passed

#1332 chore: update renFIL message
  src/components/infoTooltips/RenFILToolTip.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/ListItemWrapper.tsx
  src/modules/dashboard/lists/ListMobileItemWrapper.tsx
  src/modules/markets/MarketAssetsListItem.tsx
Labels: QC Passed, Ready for Dev Review
