Repository aave/interface, pull requests merged in 2023-04, with the labels that each got.

#1547 feat: borrow optimizations
  package.json
  src/components/transactions/Borrow/BorrowActions.tsx
  src/components/transactions/Borrow/BorrowModalContent.tsx
  src/components/transactions/Supply/SupplyActions.tsx
  src/components/transactions/utils.ts
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsList.tsx
  src/store/poolSlice.ts
  src/utils/getMaxAmountAvailableToBorrow.ts
  yarn.lock
Labels: QC Passed

#1552 feat: warning banner
  src/layouts/AppHeader.tsx
  src/layouts/MainLayout.tsx
  src/layouts/TopBarNotify.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/store/layoutSlice.ts
  src/store/root.ts
Labels: QC Passed

#1560 fix: handle stable and variable debt values in borrow list item
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsList.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListMobileItem.tsx
Labels: QC Passed, Ready for Dev Review

#1546 feat: add Scroll Alpha Testnet
  package.json
  public/icons/networks/scroll.svg
  src/ui-config/marketsConfig.tsx
  src/ui-config/networksConfig.ts
  yarn.lock
Labels: QC Passed, CI Failed

#1545 Feat: React query integration and governance hooks 1/5
  package.json
  pages/_app.page.tsx
  pages/governance/index.governance.tsx
  pages/governance/ipfs-preview.governance.tsx
  pages/governance/proposal/[proposalId].governance.tsx
  pages/governance/proposal/index.governance.tsx
  src/components/transactions/GovDelegation/DelegationTokenSelector.tsx
  src/components/transactions/GovDelegation/GovDelegationModalContent.tsx
  src/hooks/governance-data-provider/AaveTokensDataProvider.tsx
  src/hooks/governance-data-provider/GovernanceDataProvider.tsx
  src/hooks/governance-data-provider/useVotingPower.tsx
  src/hooks/governance/useGovernanceTokens.ts
  src/hooks/governance/usePowers.ts
  src/hooks/governance/useVoteOnProposal.ts
  src/hooks/governance/useVotingPowerAt.ts
  src/modules/governance/DelegatedInfoPanel.tsx
  src/modules/governance/VotingPowerInfoPanel.tsx
  src/modules/governance/proposal/VoteInfo.tsx
  src/services/GovernanceService.ts
  src/services/WalletBalanceService.ts
  src/store/governanceSlice.ts
  src/store/root.ts
  src/ui-config/SharedDependenciesProvider.tsx
  src/ui-config/queries.ts
  src/utils/types.ts
  yarn.lock
Labels: QC Passed
