Repository aave/interface, pull requests merged in 2023-07, with the labels that each got.

#1674 chore: paraswap usdt eth v3 warning
  src/components/Warnings/USDTParaswapWarning.tsx
  src/components/transactions/Repay/CollateralRepayActions.tsx
  src/components/transactions/Repay/CollateralRepayModalContent.tsx
  src/components/transactions/Swap/SwapActions.tsx
  src/components/transactions/Swap/SwapModalContent.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
Labels: QC Passed

#1683 chore: update paraswap adapters
  package.json
  src/components/Warnings/USDTParaswapWarning.tsx
  src/components/transactions/Repay/CollateralRepayActions.tsx
  src/components/transactions/Repay/CollateralRepayModalContent.tsx
  src/components/transactions/Swap/SwapActions.tsx
  src/components/transactions/Swap/SwapModalContent.tsx
  src/hooks/paraswap/common.ts
  src/hooks/paraswap/useCollateralRepaySwap.tsx
  src/hooks/paraswap/useCollateralSwap.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/ui-config/marketsConfig.tsx
  yarn.lock
Labels: QC Passed, Ready for Dev Review

#1697 feat: add ARB icon
  public/icons/tokens/arb.svg
Labels: QC Passed

#1668 feat: debt switch
  cypress/configs/v2-markets/ethereum-v2-additional.config.ts
  cypress/configs/v2-markets/ethereum-v2-full.config.ts
  cypress/configs/v3-markets/avalanche-v3-additional.config.ts
  cypress/configs/v3-markets/avalanche-v3-full.config.ts
  cypress/configs/v3-markets/polygon-v3-additional.config.ts
  cypress/configs/v3-markets/polygon-v3-full.config.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/swap.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/switch.aave-v2.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/switch.avalacnhe-v3.cy.ts
  cypress/e2e/1-v3-markets/3-polygon-v3-market/switch.polygon-v3.cy.ts
  cypress/fixtures/assets.json
  cypress/support/steps/main.steps.ts
  pages/_app.page.tsx
  src/components/infoTooltips/PriceImpactTooltip.tsx
  src/components/transactions/AssetInput.tsx
  src/components/transactions/DebtSwitch/DebtSwitchActions.tsx
  src/components/transactions/DebtSwitch/DebtSwitchModal.tsx
  src/components/transactions/DebtSwitch/DebtSwitchModalContent.tsx
  src/components/transactions/DebtSwitch/DebtSwitchModalDetails.tsx
  src/components/transactions/Repay/CollateralRepayModalContent.tsx
  src/components/transactions/Swap/SwapModalContent.tsx
  src/helpers/useTransactionHandler.tsx
  src/hooks/paraswap/common.ts
  src/hooks/paraswap/useDebtSwitch.tsx
  src/hooks/useModal.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListItem.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListMobileItem.tsx
  src/store/poolSlice.ts
  src/store/transactionsSlice.ts
  src/store/v3MigrationSlice.ts
  src/ui-config/marketsConfig.tsx
  src/utils/marketsAndNetworksConfig.ts
Labels: QC Passed

#1700 fix: safe wc v2
  package.json
  src/libs/web3-data-provider/WalletConnectConnector.ts
  src/libs/web3-data-provider/WalletOptions.ts
  src/libs/web3-data-provider/Web3Provider.tsx
  yarn.lock
Labels: QC Passed, Ready for Dev Review

#1695 fix: :bug: 1104 health factor
  src/components/transactions/Repay/RepayModalContent.tsx
  src/utils/hfUtils.ts
Labels: CI Failed
