Repository aave/interface, pull requests merged in 2023-02, with the labels that each got.

#1459 feat: Add available market on governance and staking pages
  src/components/ChainAvailabilityText.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/governance/GovernanceTopPanel.tsx
  src/modules/staking/StakingHeader.tsx
Labels: QC Passed

#1458 fix: increase credit delegation permit
  src/store/v3MigrationSelectors.ts
Labels: QC Passed, CI Passed

#1461 Feat: stETH warning on migration
  scripts/populate-cache.js
  src/components/primitives/NoData.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/migration/MigrationListItem.tsx
  src/modules/migration/MigrationListMobileItem.tsx
  src/modules/migration/StETHMigrationWarning.tsx
  src/store/v3MigrationSelectors.ts
Labels: QC Passed

#1457 feat: remove individual config and default to enable permit for all v3 testnet assets
  src/store/protocolDataSlice.ts
  src/ui-config/permitConfig.ts
Labels: QC Passed

#1456 feat: use address book package
  package.json
  src/ui-config/marketsConfig.tsx
  yarn.lock
Labels: Ready for QA Review

#1462 chore: Add cbeth icon
  public/icons/tokens/cbeth.svg
Labels: Ready for Dev Review

#1466 Smoke e2e for migration
  cypress/configs/v2-markets/avalanche-v2-additional.config.ts
  cypress/configs/v2-markets/avalanche-v2-full.config.ts
  cypress/configs/v2-markets/ethereum-v2-additional.config.ts
  cypress/configs/v2-markets/ethereum-v2-full.config.ts
  cypress/configs/v2-markets/polygon-v2-additional.config.ts
  cypress/configs/v2-markets/polygon-v2-full.config.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/migration.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/migration.polygon-v2.cy.ts
  cypress/e2e/0-v2-markets/3-avalanche-v2-market/migration.avalanche-v2.cy.ts
  cypress/fixtures/assets.json
  cypress/support/commands.ts
  cypress/support/steps/main.steps.ts
  cypress/support/steps/verification.steps.ts
  scripts/populate-cache.js
  src/modules/dashboard/DashboardTopPanel.tsx
  src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListItem.tsx
  src/modules/migration/MigrationBottomPanel.tsx
  src/modules/migration/MigrationListItem.tsx
  src/modules/migration/MigrationSelectionBox.tsx
  src/modules/migration/MigrationTopPanel.tsx
Labels: Ready for Dev Review

#1463 Feat: Proposals search & list performance
  .eslintrc.js
  cypress.config.ts
  cypress/e2e/2-settings/mobile.cy.ts
  package.json
  pages/governance/index.governance.tsx
  scripts/populate-cache.js
  src/components/NoSearchResults.tsx
  src/components/SearchInput.tsx
  src/components/TitleWithSearchBar.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/governance/ProposalListHeader.tsx
  src/modules/governance/ProposalsList.tsx
  src/modules/governance/VotingPowerInfoPanel.tsx
  src/modules/markets/MarketAssetSearchInput.tsx
  src/modules/markets/MarketAssetsListContainer.tsx
  yarn.lock
Labels: QC Passed

#1475 feat: add redirect capability migration
  scripts/populate-cache.js
  src/components/transactions/FlowCommons/Success.tsx
  src/components/transactions/MigrateV3/MigrateV3ModalContent.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
Labels: QC Passed

#1483 feat: enable v3 mainnet charts
  src/ui-config/marketsConfig.tsx
Labels: QC Passed

#1495 fix: max available to borrow calculation
  src/utils/getMaxAmountAvailableToBorrow.ts
Labels: QC Passed

#1482 fix: Small grammar and style changes to the cooldown warning.
  src/components/Warnings/CooldownWarning.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
Labels: CI Failed

#1498 fix: stable debt migration
  .prettierignore
  src/store/v3MigrationSelectors.ts
Labels: QC Passed, Ready for Dev Review

#1474 feat: swap and repay with collateral improvements
  cypress.config.ts
  cypress/support/steps/main.steps.ts
  src/components/TextWithTooltip.tsx
  src/components/Warnings/StETHCollateralWarning.tsx
  src/components/infoTooltips/StETHCollateralToolTip.tsx
  src/components/transactions/Repay/CollateralRepayModalContent.tsx
  src/components/transactions/Repay/RepayModal.tsx
  src/components/transactions/Swap/SwapModalContent.tsx
  src/components/transactions/utils.ts
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsList.tsx
  src/modules/dashboard/lists/ListItemWrapper.tsx
  src/modules/dashboard/lists/ListMobileItemWrapper.tsx
  src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListItem.tsx
  src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListMobileItem.tsx
  src/modules/reserve-overview/ReserveConfiguration.tsx
  src/static-build/proposals.json
  src/utils/hfUtils.ts
Labels: QC Passed, Ready for Dev Review, CI Passed

#1501 feat: share proposal to lens
  pages/governance/proposal/[proposalId].governance.tsx
  public/icons/lens-logo.svg
  src/components/transactions/FlowCommons/Success.tsx
  src/components/transactions/GovVote/GovVoteModalContent.tsx
  src/components/transactions/MigrateV3/MigrateV3ModalContent.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
Labels: QC Passed, Ready for Dev Review
