Repository aave/interface, pull requests merged in 2023-03, with the labels that each got.

#1504 feat: display asset with max supply cap
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListItem.tsx
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListMobileItem.tsx
Labels: QC Passed, CI Passed

#1497 Feat: New delegation section
  .eslintrc.js
  pages/governance/index.governance.tsx
  src/components/Avatar.tsx
  src/components/CompactableTypography.tsx
  src/components/TextWithTooltip.tsx
  src/components/UserDisplay.tsx
  src/components/UserNameText.tsx
  src/components/badges/ExclamationBadge.tsx
  src/layouts/WalletWidget.tsx
  src/libs/web3-data-provider/Web3Provider.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/governance/DelegatedInfoPanel.tsx
  src/modules/governance/ProposalListHeader.tsx
  src/modules/governance/ProposalsList.tsx
  src/modules/governance/UserGovernanceInfo.tsx
  src/modules/governance/VotingPowerInfoPanel.tsx
  src/store/root.ts
  src/store/utils/domain-fetchers/ens.ts
  src/store/utils/domain-fetchers/index.ts
  src/store/walletDomains.ts
  src/store/walletSlice.ts
  src/utils/tFetch.ts
Labels: QC Passed

#1510 fix: don't override default padding right for MuiSelect in market switcher
  src/components/MarketSwitcher.tsx
Labels: QC Passed

#1516 fix/1515-polygon-bridge-link
  src/ui-config/networksConfig.ts
Labels: Ready for QA Review, Ready for Dev Review, CI Failed

#1514 Feat/sepolia testnet
  package.json
  src/components/MarketSwitcher.tsx
  src/ui-config/marketsConfig.tsx
  src/ui-config/networksConfig.ts
  src/utils/marketsAndNetworksConfig.ts
  yarn.lock
Labels: QC Passed, Ready for Dev Review, CI Passed

#1512 feat: wrapped asset withdraw/borrow modal improvements
  public/icons/tokens/matic.svg
  public/icons/tokens/wavax.svg
  public/icons/tokens/wmatic.svg
  src/components/icons/LensIcon.tsx
  src/components/icons/WalletIcon.tsx
  src/components/transactions/Borrow/BorrowActions.tsx
  src/components/transactions/Borrow/BorrowModalContent.tsx
  src/components/transactions/FlowCommons/TxModalDetails.tsx
  src/components/transactions/Supply/SupplyActions.tsx
  src/components/transactions/Supply/SupplyModalContent.tsx
  src/components/transactions/Withdraw/WithdrawModalContent.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/reserve-overview/AddTokenDropdown.tsx
  src/modules/reserve-overview/ReserveActions.tsx
  src/modules/reserve-overview/TokenLinkDropdown.tsx
  src/store/poolSlice.ts
Labels: QC Passed, Ready for Dev Review, CI Passed

#1496 feat: setup tests for local execution
  cypress/README.md
  cypress/configs/local/full.config.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/dai.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/migration.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/1-amm-v2-market/0-assets/wbtc.amm-v2.cy.ts
  cypress/e2e/0-v2-markets/3-avalanche-v2-market/migration.avalanche-v2.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/0-assets/dai.avalanche-v3.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/0-assets/usdc.avalanche-v3.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/0-assets/usdt.avalacnhe-v3.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/e-mode.avalanche-v3.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/swap.avalanche-v3.cy.ts
  cypress/e2e/1-v3-markets/3-polygon-v3-market/e-mode.polygon-v3.cy.ts
  cypress/e2e/2-settings/wallet-connect.cy.ts
  cypress/plugins/index.js
  package.json
  src/layouts/WalletWidget.tsx
Labels: Ready for Dev Review

#1528 chore: zero ltv withdraw check
  src/components/transactions/CollateralChange/CollateralChangeModalContent.tsx
  src/components/transactions/Repay/CollateralRepayModalContent.tsx
  src/components/transactions/Swap/SwapModalContent.tsx
  src/components/transactions/Withdraw/WithdrawModalContent.tsx
  src/components/transactions/utils.ts
  src/locales/en/messages.js
  src/locales/en/messages.po
Labels: QC Passed

#1523 feat: add busd warning message
  src/components/Warnings/BUSDOffBoardingWarning.tsx
  src/components/infoTooltips/BUSDOffboardingToolTip.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/ListItemWrapper.tsx
  src/modules/dashboard/lists/ListMobileItemWrapper.tsx
  src/modules/markets/MarketAssetsListItem.tsx
  src/modules/reserve-overview/ReserveConfiguration.tsx
Labels: good first issue, QC Passed

#1499 Feat: new delegation modal
  .github/workflows/build-test-deploy.yml
  .github/workflows/test-deploy-fork.yml
  cypress/configs/governance-stake.config.ts
  cypress/configs/v2-markets/ethereum-v2-additional.config.ts
  cypress/configs/v2-markets/ethereum-v2-full.config.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/stake.aave-v2.cy.ts
  cypress/e2e/3-stake-governance/governance-deligation.cy.ts
  cypress/e2e/3-stake-governance/stake.cy.ts
  cypress/fixtures/assets.json
  cypress/support/steps/governance.steps.ts
  cypress/support/steps/stake.steps.ts
  src/components/transactions/GovDelegation/DelegationTokenSelector.tsx
  src/components/transactions/GovDelegation/DelegationTypeSelector.tsx
  src/components/transactions/GovDelegation/GovDelegationActions.tsx
  src/components/transactions/GovDelegation/GovDelegationModal.tsx
  src/components/transactions/GovDelegation/GovDelegationModalContent.tsx
  src/components/transactions/utils.ts
  src/helpers/types.ts
  src/hooks/governance-data-provider/AaveTokensDataProvider.tsx
  src/hooks/useModal.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/governance/DelegatedInfoPanel.tsx
  src/modules/governance/VotingPowerInfoPanel.tsx
  src/store/governanceSlice.ts
Labels: QC Passed, CI Passed

#1520 feat: add long executor label in governance
  src/modules/governance/ProposalListItem.tsx
  src/modules/governance/ProposalsList.tsx
Labels: QC Passed, Ready for Dev Review

#1530 fix: price impact calculations
  src/components/transactions/Repay/CollateralRepayModalContent.tsx
  src/components/transactions/Swap/SwapModalContent.tsx
Labels: QC Passed, Ready for QA Review

#1534 fix: collateral swap hf and swap target collateralization details
  cypress/e2e/0-v2-markets/0-main-v2-market/critical-conditions.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/migration.polygon-v2.cy.ts
  cypress/e2e/0-v2-markets/3-avalanche-v2-market/critical-conditions.avalanche-v2.cy.ts
  cypress/e2e/0-v2-markets/3-avalanche-v2-market/migration.avalanche-v2.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/0-assets/avax.avalanche-v3.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/critical-conditions.avalanche-v3.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/swap.avalanche-v3.cy.ts
  cypress/e2e/1-v3-markets/4-optimism-v3-market/0-assets/wbtc.optimism-v3.cy.ts
  src/components/isolationMode/IsolatedBadge.tsx
  src/components/isolationMode/IsolatedTooltip.tsx
  src/components/transactions/FlowCommons/TxModalDetails.tsx
  src/components/transactions/Supply/SupplyModalContent.tsx
  src/components/transactions/Swap/SwapModalContent.tsx
  src/components/transactions/Swap/SwapModalDetails.tsx
  src/components/transactions/utils.ts
  src/helpers/types.ts
  src/hooks/useAssetCaps.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/ListItemIsolationBadge.tsx
  src/modules/migration/MigrationListItem.tsx
  src/modules/migration/MigrationListItemToggler.tsx
  src/modules/migration/MigrationListMobileItem.tsx
Labels: QC Passed
