Repository aave/interface, pull requests merged in 2023-08, with the labels that each got.

#1679 fix: inexplicit small amount message when repay
  src/hooks/paraswap/common.ts
  src/hooks/paraswap/useCollateralRepaySwap.tsx
  src/hooks/paraswap/useCollateralSwap.tsx
  src/hooks/paraswap/useDebtSwitch.tsx
Labels: CI Failed

#1729 fix: don't show gho in collateral swap targets
  src/components/transactions/Swap/SwapModalContent.tsx
Labels: QC Passed, Ready for Dev Review

#1732 feat: markets sort by tvl
  cypress/e2e/0-v2-markets/0-main-v2-market/swap.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/switch.aave-v2.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/swap.avalanche-v3.cy.ts
  cypress/e2e/1-v3-markets/3-polygon-v3-market/swap.polygon-v3.cy.ts
  cypress/e2e/1-v3-markets/3-polygon-v3-market/switch.polygon-v3.cy.ts
  src/modules/markets/MarketAssetsListContainer.tsx
  src/store/poolSelectors.ts
Labels: QC Passed

#1734 fix: paraswap fee redirection
  package.json
  src/hooks/paraswap/common.ts
  yarn.lock
Labels: CI Failed

#1692 fix: :bug: fix bug 1671
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsList.tsx
Labels: CI Failed

#1731 refactoring tests
  .github/workflows/build-test-deploy.yml
  .github/workflows/test-deploy-fork.yml
  cypress/configs/v2-markets/amm-v2-full.config.ts
  cypress/configs/v2-markets/amm-v2-smoke.config.ts
  cypress/configs/v2-markets/avalanche-v2-full.config.ts
  cypress/configs/v2-markets/avalanche-v2-smoke.config.ts
  cypress/configs/v2-markets/ethereum-v2-full.config.ts
  cypress/configs/v2-markets/ethereum-v2-smoke.config.ts
  cypress/configs/v2-markets/polygon-v2-full.config.ts
  cypress/configs/v2-markets/polygon-v2-smoke.config.ts
  cypress/configs/v3-markets/avalanche-v3-full.config.ts
  cypress/configs/v3-markets/ethereum-v3-full.config.ts
  cypress/configs/v3-markets/optimism-v3-full.config.ts
  cypress/configs/v3-markets/optimism-v3-smoke.config.ts
  cypress/configs/v3-markets/polygon-v3-full.config.ts
  cypress/configs/v3-markets/polygon-v3-smoke.config.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/bat.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/mana.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/mkr.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/ren.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/tusd.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/critical-conditions.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/1-amm-v2-market/0-assets/dai.amm-v2.cy.ts
  cypress/e2e/0-v2-markets/1-amm-v2-market/0-assets/eth.amm-v2.cy.ts
  cypress/e2e/0-v2-markets/1-amm-v2-market/0-assets/usdc.amm-v2.cy.ts
  cypress/e2e/0-v2-markets/1-amm-v2-market/0-assets/usdt.amm-v2.cy.ts
  cypress/e2e/0-v2-markets/1-amm-v2-market/0-assets/wbtc.amm-v2.cy.ts
  cypress/e2e/0-v2-markets/1-amm-v2-market/critical-conditions.amm-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/bal.polygon-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/crv.polygon-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/dai.polygon-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/dpi.polygon-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/ghst.polygon-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/link.polygon-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/matic.polygon-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/sushi.polygon-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/usdt.polygon-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/wbtc.polygon-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/weth.polygon-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/swap.polygon-v2.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/0-assets/avax.avalanche-v3.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/0-assets/dai.avalanche-v3.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/e-mode.avalanche-v3.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/isolated-mode.avalanche-v3.cy.ts
  cypress/e2e/4-gho-ethereum/gho-discount-dashboard.gho-v3.cy.ts
  cypress/support/helpers/dashboard.helper.ts
  cypress/support/steps/configuration.steps.ts
  cypress/support/steps/main.steps.ts
  cypress/support/tools/tenderly.ts
Labels: Ready for Dev Review

#1750 fix: liquidity check for debt switch
  src/components/transactions/DebtSwitch/DebtSwitchModalContent.tsx
Labels: QC Passed

#1752 fix: gho debt switch liquidity check
  src/components/transactions/DebtSwitch/DebtSwitchModalContent.tsx
Labels: QC Passed

#1753 feat: add Scroll Sepolia testnet, remove Scroll Alpha
  package.json
  public/icons/networks/scroll.svg
  src/ui-config/marketsConfig.tsx
  src/ui-config/networksConfig.ts
  yarn.lock
Labels: CI Failed

#1709 chore: testnets upgrade
  .env.example
  .github/actions/build/action.yml
  custom.d.ts
  package.json
  pages/faucet.page.tsx
  src/components/transactions/Faucet/CaptchaFaucetModalContent.tsx
  src/components/transactions/Faucet/FaucetModal.tsx
  src/components/transactions/Faucet/FaucetModalContent.tsx
  src/components/transactions/Faucet/Turnstile.tsx
  src/components/transactions/Faucet/utils.ts
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/store/poolSlice.ts
  src/store/root.ts
  src/ui-config/marketsConfig.tsx
  yarn.lock
Labels: QC Passed, Ready for Dev Review
