Repository aave/interface, pull requests merged in 2023-01, with the labels that each got.

#1385 feat: support load fork using process.env at dev and Github CI
  .env.development
  .env.example
  .github/actions/build/action.yml
  .github/workflows/build-test-deploy.yml
  custom.d.ts
  src/utils/marketsAndNetworksConfig.ts
Labels: QC Passed

#1372 feat: add sort into positions dashboard
  cypress/e2e/1-v3-markets/3-polygon-v3-market/e-mode.polygon-v3.cy.ts
  src/components/lists/ListColumn.tsx
  src/locales/en/messages.po
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsList.tsx
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListItem.tsx
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListMobileItem.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsList.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListItem.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListMobileItem.tsx
  src/modules/dashboard/lists/ListButtonsColumn.tsx
  src/modules/dashboard/lists/ListHeader.tsx
  src/modules/dashboard/lists/ListItemWrapper.tsx
  src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsList.tsx
  src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListItem.tsx
  src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListMobileItem.tsx
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsList.tsx
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListItem.tsx
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListMobileItem.tsx
  src/utils/dashboardSortUtils.ts
Labels: QC Passed, Ready for Dev Review

#1393 chore: update to utils for v2 -> v3 migration support
  package.json
  yarn.lock
Labels: QC Passed

#1414 chore: add in height integration for opened issues
  .github/workflows/sync-height-issue-opened.yml
  scripts/populate-cache.js
Labels: Ready for Dev Review

#1359 feat: permissioned faucets
  .env.example
  .github/actions/build/action.yml
  custom.d.ts
  cypress/support/steps/verification.steps.ts
  package.json
  pages/faucet.page.tsx
  src/components/icons/WalletIcon.tsx
  src/components/transactions/Faucet/CaptchaFaucetModalContent.tsx
  src/components/transactions/Faucet/FaucetModal.tsx
  src/components/transactions/Faucet/FaucetModalContent.tsx
  src/components/transactions/Faucet/Turnstile.tsx
  src/components/transactions/Faucet/utils.ts
  src/components/transactions/FlowCommons/Success.tsx
  src/helpers/useTransactionHandler.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/store/governanceSlice.ts
  src/store/incentiveSlice.ts
  src/store/poolSlice.ts
  src/store/protocolDataSlice.ts
  src/store/root.ts
  src/store/stakeSlice.ts
  src/store/walletSlice.ts
  src/ui-config/marketsConfig.tsx
  yarn.lock
Labels: QC Passed, Ready for Dev Review

#1399 feat: paraswap permit
  cypress/support/steps/main.steps.ts
  scripts/populate-cache.js
  src/components/transactions/FlowCommons/ApprovalMethodToggleButton.tsx
  src/components/transactions/Repay/CollateralRepayActions.tsx
  src/components/transactions/Repay/CollateralRepayModalContent.tsx
  src/components/transactions/Swap/SwapActions.tsx
  src/components/transactions/Swap/SwapModalContent.tsx
  src/components/transactions/Warnings/ParaswapErrorDisplay.tsx
  src/helpers/useParaSwapTransactionHandler.tsx
  src/hooks/paraswap/common.ts
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/store/poolSlice.ts
Labels: QC Passed, Ready for Dev Review

#1423 fix: allow to delegate if already delegating
  src/modules/governance/VotingPowerInfoPanel.tsx
Labels: QC Passed

#1428 fix: make tables in markdown render somewhat correctly
  pages/governance/proposal/[proposalId].governance.tsx
Labels: QC Passed, CI Failed

#1431 feat: use arbiscan on test and prod
  src/ui-config/networksConfig.ts
Labels: CI Passed

#1426 fix: show assets with maxed out debt cieling in borrow list
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/0-assets/usdt.avalacnhe-v3.cy.ts
  scripts/populate-cache.js
  src/components/transactions/Borrow/BorrowModalContent.tsx
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListItem.tsx
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListMobileItem.tsx
Labels: QC Passed

#1442 feature: migration v2-v3 avalanche and Polygon [skip cypress]
  package.json
  pages/_app.page.tsx
  pages/v3-migration.page.tsx
  scripts/populate-cache.js
  src/components/MarketSwitcher.tsx
  src/components/TopInfoPanel/PageTitle.tsx
  src/components/TopInfoPanel/TopInfoPanel.tsx
  src/components/incentives/IncentivesCard.tsx
  src/components/infoTooltips/MigrationDisabledTooltip.tsx
  src/components/lists/ListHeaderTitle.tsx
  src/components/primitives/Link.tsx
  src/components/primitives/Row.tsx
  src/components/transactions/Borrow/BorrowActions.tsx
  src/components/transactions/FlowCommons/ModalWrapper.tsx
  src/components/transactions/FlowCommons/Success.tsx
  src/components/transactions/MigrateV3/MigrateV3Actions.tsx
  src/components/transactions/MigrateV3/MigrateV3Modal.tsx
  src/components/transactions/MigrateV3/MigrateV3ModalAssetsList.tsx
  src/components/transactions/MigrateV3/MigrateV3ModalContent.tsx
  src/components/transactions/Repay/RepayActions.tsx
  src/components/transactions/Stake/StakeActions.tsx
  src/components/transactions/Supply/SupplyActions.tsx
  src/components/transactions/Warnings/IsolationModeWarning.tsx
  src/components/transactions/Withdraw/WithdrawActions.tsx
  src/helpers/useTransactionHandler.tsx
  src/hooks/app-data-provider/useAppDataProvider.tsx
  src/hooks/useIsWrongNetwork.tsx
  src/hooks/useModal.tsx
  src/hooks/useUserReserves.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/DashboardTopPanel.tsx
  src/modules/dashboard/lists/ListItemUsedAsCollateral.tsx
  src/modules/migration/HFChange.tsx
  src/modules/migration/MigrationBottomPanel.tsx
  src/modules/migration/MigrationList.tsx
  src/modules/migration/MigrationListBorrowItem.tsx
  src/modules/migration/MigrationListItem.tsx
  src/modules/migration/MigrationListItemLoader.tsx
  src/modules/migration/MigrationListItemToggler.tsx
  src/modules/migration/MigrationListMobileItem.tsx
  src/modules/migration/MigrationLists.tsx
  src/modules/migration/MigrationMobileList.tsx
  src/modules/migration/MigrationSelectionBox.tsx
  src/modules/migration/MigrationTopPanel.tsx
  src/store/poolSelectors.ts
  src/store/poolSlice.ts
  src/store/root.ts
  src/store/v3MigrationSelectors.ts
  src/store/v3MigrationSlice.ts
  src/ui-config/marketsConfig.tsx
  src/ui-config/networksConfig.ts
  src/utils/theme.tsx
  yarn.lock
Labels: QC Passed, CI Failed

#1447 feat: v3 ethereum migration [skip cypress]
  src/ui-config/marketsConfig.tsx
Labels: CI Failed

#1455 fix: staking approval
  cypress/e2e/0-v2-markets/0-main-v2-market/stake.aave-v2.cy.ts
  package.json
  src/components/transactions/Stake/StakeActions.tsx
  yarn.lock
Labels: QC Passed

#1448 Tests/v3 ethereum
  .github/workflows/build-test-deploy.yml
  .github/workflows/test-deploy-fork.yml
  cypress/configs/v2-markets/ethereum-v2-additional.config.ts
  cypress/configs/v3-markets/ethereum-v3-additional.config.ts
  cypress/configs/v3-markets/ethereum-v3-full.config.ts
  cypress/configs/v3-markets/ethereum-v3-smoke.config.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/tusd.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/usdc.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/usdt.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/0-main-v2-market/stake.aave-v2.cy.ts
  cypress/e2e/1-v3-markets/0-ethereum-v3-market/0-assets/dai.ethereum-v3.cy.ts
  cypress/e2e/1-v3-markets/0-ethereum-v3-market/0-assets/eth.ethereum-v3.cy.ts
  cypress/e2e/1-v3-markets/0-ethereum-v3-market/0-assets/link.ethereum-v3.cy.ts
  cypress/e2e/1-v3-markets/0-ethereum-v3-market/0-assets/usdc.ethereum-v3.cy.ts
  cypress/e2e/1-v3-markets/0-ethereum-v3-market/0-assets/wbtc.ethereum-v3.cy.ts
  cypress/e2e/1-v3-markets/0-ethereum-v3-market/0-assets/wsteth.ethereum-v3.cy.ts
  cypress/e2e/1-v3-markets/0-ethereum-v3-market/critical-conditions.ethereum-v3.cy.ts
  cypress/e2e/1-v3-markets/0-ethereum-v3-market/e-mode.ethereum-v3.cy.ts
  cypress/e2e/1-v3-markets/0-ethereum-v3-market/swap.ethereum-v3.cy.ts
  cypress/e2e/1-v3-markets/3-polygon-v3-market/0-assets/eurs.polygon-v3.cy.ts
  cypress/e2e/1-v3-markets/3-polygon-v3-market/e-mode.polygon-v3.cy.ts
  cypress/e2e/1-v3-markets/3-polygon-v3-market/isolated-and-emode.polygon-v3.cy.ts
  cypress/e2e/1-v3-markets/3-polygon-v3-market/isolated-mode.polygon-v3.cy.ts
  cypress/fixtures/assets.json
  cypress/support/steps/configuration.steps.ts
  cypress/support/steps/main.steps.ts
  scripts/populate-cache.js
  src/hooks/useReserveActionState.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListItem.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListMobileItem.tsx
  src/modules/reserve-overview/ReserveActions.tsx
  src/modules/reserve-overview/ReserveTopDetails.tsx
  src/utils/getMaxAmountAvailableToBorrow.ts
  src/utils/getMaxAmountAvailableToSupply.ts
Labels: Ready for Dev Review
