Repository aave/interface, pull requests merged in 2023-10, with the labels that each got.

#1795 chore: move tx history locations
  pages/index.page.tsx
  src/layouts/WalletWidget.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/DashboardContentWrapper.tsx
  src/modules/dashboard/DashboardTopPanel.tsx
Labels: QC Passed

#1796 feat: move from ethereum-blockies-base64 to blo
  package.json
  src/components/Avatar.tsx
  src/components/UserDisplay.tsx
  src/libs/hooks/use-get-ens.tsx
  src/modules/governance/proposal/VotersListItem.tsx
  yarn.lock
Labels: CI Failed

#1802 fix: dynamically load modals
  .github/actions/dev-ipfs-pin/action.yml
  .github/actions/production-ipfs-pin/action.yml
  .github/workflows/build-test-deploy-dev.yml
  cypress/configs/v3-markets/base-v3-smoke.config.ts
  cypress/e2e/1-v3-markets/3-polygon-v3-market/switch.polygon-v3.cy.ts
  package.json
  pages/_app.page.tsx
  pages/faucet.page.tsx
  pages/governance/index.governance.tsx
  pages/governance/ipfs-preview.governance.tsx
  pages/governance/proposal/[proposalId].governance.tsx
  pages/governance/proposal/index.governance.tsx
  pages/staking.staking.tsx
  pages/v3-migration.page.tsx
  src/components/WalletConnection/ConnectWalletButton.tsx
  src/layouts/AppHeader.tsx
  yarn.lock
Labels: QC Passed, Ready for Dev Review

#1814 fix: add patch in for legacy KNC token
  public/icons/tokens/kncl.svg
  src/ui-config/reservePatches.ts
Labels: Ready for QA Review, Ready for Dev Review

#1806 fix: off boarding warnings
  cypress/e2e/1-v3-markets/3-polygon-v3-market/switch.polygon-v3.cy.ts
  src/components/Warnings/BUSDOffBoardingWarning.tsx
  src/components/Warnings/OffboardingWarning.tsx
  src/components/infoTooltips/OffboardingToolTip.tsx
  src/locales/en/messages.po
  src/modules/dashboard/lists/ListItemWrapper.tsx
  src/modules/dashboard/lists/ListMobileItemWrapper.tsx
  src/modules/markets/MarketAssetsListItem.tsx
  src/modules/markets/MarketAssetsListMobileItem.tsx
  src/modules/reserve-overview/ReserveConfiguration.tsx
  src/modules/reserve-overview/TokenLinkDropdown.tsx
Labels: QC Passed, Ready for Dev Review

#1797 chore: rename lenster to hey
  pages/governance/proposal/[proposalId].governance.tsx
  src/components/icons/HeyIcon.tsx
  src/components/transactions/Borrow/GhoBorrowSuccessView.tsx
  src/components/transactions/GovVote/GovVoteModalContent.tsx
  src/layouts/AppFooter.tsx
  src/utils/mixPanelEvents.ts
Labels: CI Failed
