Repository aave/interface, pull requests merged in 2023-06, with the labels that each got.

#1596 chore(deps): bump aave-address-book to 1.23.1, fixing Scroll Alpha deployment
  package.json
  yarn.lock
Labels: QC Passed, CI Failed

#1601 feat: usd borrow target utilization [skip cypress]
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/reserve-overview/graphs/InterestRateModelGraph.tsx
  src/modules/reserve-overview/graphs/InterestRateModelGraphContainer.tsx
Labels: QC Passed

#1626 fix: ci tests and estimate gas failure
  cypress/e2e/0-v2-markets/0-main-v2-market/critical-conditions.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/critical-conditions.polygon-v2.cy.ts
  cypress/e2e/1-v3-markets/0-ethereum-v3-market/critical-conditions.ethereum-v3.cy.ts
  cypress/e2e/1-v3-markets/1-arbitrum-v3-market/critical-conditions.arbitrum-v3.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/critical-conditions.avalanche-v3.cy.ts
  cypress/e2e/1-v3-markets/3-polygon-v3-market/critical-conditions.polygon-v3.cy.ts
  cypress/e2e/1-v3-markets/4-optimism-v3-market/critical-conditions.optimism-v3.cy.ts
  cypress/e2e/3-stake-governance/governance-deligation.cy.ts
  cypress/e2e/3-stake-governance/stake.cy.ts
  cypress/support/steps/stake.steps.ts
  cypress/support/tools/bridge.ts
  package.json
  src/utils/getMaxAmountAvailableToBorrow.ts
  yarn.lock
Labels: Ready for Dev Review

#1633 fix: handle short description missing [skip cypress]
  pages/governance/index.governance.tsx
Labels: QC Passed, Ready for Dev Review

#1642 Feat/amm warning message
  .github/workflows/build-test-deploy.yml
  .github/workflows/test-deploy-fork.yml
  src/components/transactions/Warnings/MarketWarning.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsList.tsx
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsList.tsx
  src/modules/markets/MarketAssetsListContainer.tsx
  src/static-build/ipfsFiles.json
  src/ui-config/marketsConfig.tsx
Labels: QC Passed

#1629 chore: Arbitrum bridged usdc reserve patch
  src/ui-config/reservePatches.ts
Labels: QC Passed

#1643 fix: use max uint value for approval amount
  src/store/poolSlice.ts
Labels: QC Passed, Ready for Dev Review

#1645 feat: add amm migration helper
  package.json
  src/modules/migration/MigrationBottomPanel.tsx
  src/modules/migration/MigrationTopPanel.tsx
  src/store/poolSelectors.ts
  src/ui-config/marketsConfig.tsx
  yarn.lock
Labels: QC Passed, Ready for Dev Review, CI Passed

#1650 Feat/remove fiat/on ramp
  .env.development
  .env.example
  .github/actions/build/action.yml
  .github/workflows/build-test-deploy.yml
  custom.d.ts
  src/hooks/useCryptoBuyAvailable.tsx
  src/modules/reserve-overview/ReserveActions.tsx
  src/modules/staking/BuyWithFiat.tsx
  src/ui-config/menu-items/index.tsx
Labels: QC Passed

#1651 fix: moving assets breaks interface
  src/components/TextWithTooltip.tsx
  src/components/lists/ListWrapper.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsList.tsx
  src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsList.tsx
Labels: QC Passed, CI Passed

#1470 feat: Updates `WalletConnect` to `v2`
  .env.development
  .env.example
  .github/actions/build/action.yml
  .github/workflows/build-test-deploy.yml
  custom.d.ts
  cypress/e2e/2-settings/wallet-connect.cy.ts
  package.json
  pages/_app.page.tsx
  public/icons/networks/metis.svg
  src/components/WalletConnection/WalletSelector.tsx
  src/libs/web3-data-provider/WalletConnectConnector.ts
  src/libs/web3-data-provider/WalletOptions.ts
  src/libs/web3-data-provider/Web3Provider.tsx
  src/static-build/proposals.json
  src/styles/variables.css
  yarn.lock
Labels: QC Passed

#1658 chore: update version banner
  src/components/MarketSwitcher.tsx
Labels: QC Passed

#1670 fix: remove auto focus on address input
  src/components/WalletConnection/WalletSelector.tsx
Labels: QC Passed, Ready for Dev Review
