Repository aave/interface, pull requests merged in 2023-11, with the labels that each got.

#1824 chore: show usd values on assets for supply
  cypress/e2e/5-widgets/switch-tool.cy.ts
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListItem.tsx
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListItem.tsx
Labels: QC Passed

#1822 fix: typos in comments
  cypress/support/steps/main.steps.ts
  cypress/support/steps/verification.steps.ts
  src/helpers/useTransactionHandler.tsx
  src/hooks/useTransactionHistory.tsx
Labels: CI Passed

#1826 feat: gnosis market [skip cypress]
  package.json
  public/icons/networks/gnosis.svg
  public/icons/tokens/eure.svg
  public/icons/tokens/gno.svg
  public/icons/tokens/gnosissdai.svg
  public/icons/tokens/wxdai.svg
  public/icons/tokens/xdai.svg
  src/ui-config/marketsConfig.tsx
  src/ui-config/networksConfig.ts
  src/ui-config/reservePatches.ts
  yarn.lock
Labels: QC Passed

#1827 feat: add arb pokt rpc
  src/ui-config/networksConfig.ts
Labels: QC Passed

#1838 feat: rates history for base and metis
  src/ui-config/networksConfig.ts
Labels: QC Passed

#1850 chore: remove notify messages [skip cypress]
  src/layouts/MainLayout.tsx
Labels: QC Passed

#1852 fix: test coverage for stake and gho-modal
  cypress/e2e/2-settings/stake-abpt.cy.ts
  cypress/e2e/4-gho-ethereum/fixtures/gho.json
  cypress/e2e/5-widgets/switch-tool.cy.ts
Labels: Ready for Dev Review

#1853 Test/gnosis coverage
  .github/workflows/build-test-deploy-dev.yml
  .github/workflows/build-test-deploy.yml
  .github/workflows/test-deploy-fork.yml
  cypress/configs/v3-markets/gnosis-v3-smoke.config.ts
  cypress/e2e/1-v3-markets/7-gnosis-v3-market/0-assets/usdc.gnosis-v3.cy.ts
  cypress/e2e/1-v3-markets/7-gnosis-v3-market/0-assets/xdai.gnosis-v3.cy.ts
  cypress/fixtures/assets.json
  cypress/support/steps/configuration.steps.ts
Labels: Ready for Dev Review

#1866 fix: native vs. bridged USDC naming
  cypress/fixtures/assets.json
  src/ui-config/reservePatches.ts
Labels: QC Passed, Ready for Dev Review
