Repository aave/interface, pull requests merged in 2023-05, with the labels that each got.

#1566 test: improve stability of collateral repay tests
  cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/ren.aave-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/usdc.polygon-v2.cy.ts
  cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/usdt.polygon-v2.cy.ts
  cypress/e2e/0-v2-markets/3-avalanche-v2-market/0-assets/usdc.avalanche-v2.cy.ts
  cypress/e2e/0-v2-markets/3-avalanche-v2-market/0-assets/usdt.avalanche-v2.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/0-assets/usdc.avalanche-v3.cy.ts
  cypress/e2e/1-v3-markets/2-avalanche-v3-market/0-assets/usdt.avalacnhe-v3.cy.ts
  cypress/e2e/1-v3-markets/3-polygon-v3-market/0-assets/link.polygon-v3.cy.ts
  cypress/e2e/1-v3-markets/3-polygon-v3-market/0-assets/usdc.polygon-v3.cy.ts
  cypress/e2e/1-v3-markets/3-polygon-v3-market/0-assets/usdt.polygon-v3.cy.ts
  cypress/e2e/1-v3-markets/4-optimism-v3-market/0-assets/usdc.optimism-v3.cy.ts
  cypress/e2e/1-v3-markets/4-optimism-v3-market/0-assets/usdt.optimism-v3.cy.ts
Labels: Ready for Dev Review

#1578 Fix: Remove extra header column in ListLoader
  src/locales/en/messages.po
  src/modules/dashboard/lists/ListHeader.tsx
Labels: QC Passed

#1565 fix: migration credit delegation tx approval
  package.json
  src/store/v3MigrationSelectors.ts
  yarn.lock
Labels: QC Passed

#1563 fix: apply gas limit estimation helper
  src/components/transactions/Borrow/BorrowActions.tsx
  src/components/transactions/Supply/SupplyActions.tsx
  src/store/poolSlice.ts
Labels: QC Passed

#1589 fix: make sure reserve can be an isolated asset
  src/components/transactions/Swap/SwapModalContent.tsx
Labels: QC Passed, Ready for Dev Review

#1595 fix: top voters query
  cypress/e2e/1-v3-markets/0-ethereum-v3-market/0-assets/wsteth.ethereum-v3.cy.ts
  cypress/e2e/1-v3-markets/0-ethereum-v3-market/e-mode.ethereum-v3.cy.ts
  cypress/fixtures/assets.json
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/governance/proposal/VotersList.tsx
  src/modules/governance/proposal/VotersListContainer.tsx
  src/modules/governance/proposal/VotersListItem.tsx
Labels: QC Passed

#1598 chore: update staking helper version
  .env.development
  cypress/e2e/3-stake-governance/stake.cy.ts
  cypress/support/steps/stake.steps.ts
  package.json
  pages/staking.staking.tsx
  src/components/Warnings/CooldownWarning.tsx
  src/components/transactions/Stake/StakeModalContent.tsx
  src/components/transactions/StakeCooldown/StakeCooldownActions.tsx
  src/components/transactions/StakeCooldown/StakeCooldownModalContent.tsx
  src/components/transactions/StakeRewardClaim/StakeRewardClaimModalContent.tsx
  src/components/transactions/UnStake/UnStakeModalContent.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/staking/StakeActionBox.tsx
  src/modules/staking/StakingPanel.tsx
  src/store/stakeSlice.ts
  src/ui-config/stakeConfig.ts
  yarn.lock
Labels: QC Passed, Ready for Dev Review

#1549 Feat: staking hooks 3/5
  pages/staking.staking.tsx
  src/components/transactions/Stake/StakeModalContent.tsx
  src/components/transactions/StakeCooldown/StakeCooldownModalContent.tsx
  src/components/transactions/StakeRewardClaim/StakeRewardClaimModalContent.tsx
  src/components/transactions/UnStake/UnStakeModalContent.tsx
  src/helpers/useTransactionHandler.tsx
  src/hooks/stake/useGeneralStakeUiData.ts
  src/hooks/stake/useUserStakeUiData.ts
  src/modules/staking/StakingPanelNoWallet.tsx
  src/services/UiStakeDataService.ts
  src/store/root.ts
  src/store/stakeSlice.ts
  src/ui-config/SharedDependenciesProvider.tsx
  src/ui-config/queries.ts
Labels: QC Passed

#1613 fix: Warning bar in wallet menu on mobile
  src/layouts/AppHeader.tsx
  src/layouts/TopBarNotify.tsx
  src/store/layoutSlice.ts
Labels: QC Passed, CI Failed

#1617 chore: remove polygon message and enable features [skip cypress]
  cypress/e2e/0-v2-markets/2-polygon-v2-market/migration.polygon-v2.cy.ts
  src/components/transactions/Warnings/MarketWarning.tsx
  src/hooks/useReserveActionState.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/DashboardContentWrapper.tsx
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListItem.tsx
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListMobileItem.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListItem.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListMobileItem.tsx
  src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListItem.tsx
  src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListMobileItem.tsx
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListItem.tsx
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListMobileItem.tsx
  src/modules/markets/MarketAssetsListContainer.tsx
Labels: QC Passed

#1602 feat: change swap to switch
  cypress/support/steps/main.steps.ts
  src/components/Warnings/StETHCollateralWarning.tsx
  src/components/infoTooltips/PriceImpactTooltip.tsx
  src/components/transactions/Swap/SwapActions.tsx
  src/components/transactions/Swap/SwapModal.tsx
  src/components/transactions/Swap/SwapModalContent.tsx
  src/components/transactions/Swap/SwapModalDetails.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListItem.tsx
  src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListMobileItem.tsx
Labels: QC Passed

#1615 fix: migration with credit delegation signature
  src/store/v3MigrationSelectors.ts
  src/store/v3MigrationSlice.ts
Labels: QC Passed
