Repository aave/interface, pull requests merged in 2024-02, with the labels that each got.

#1951 Feat/ add staking tokens to switch
  src/ui-config/TokenList.ts
Labels: QC Passed

#1848 feat: abpt v2
  package.json
  pages/_app.page.tsx
  pages/staking.staking.tsx
  public/icons/tokens/stkbptv2.svg
  src/components/transactions/Stake/StakeActions.tsx
  src/components/transactions/Stake/StakeModalContent.tsx
  src/components/transactions/StakeCooldown/StakeCooldownModal.tsx
  src/components/transactions/StakeCooldown/StakeCooldownModalContent.tsx
  src/components/transactions/StakeRewardClaim/StakeRewardClaimModalContent.tsx
  src/components/transactions/StakeRewardClaimRestake/StakeRewardClaimRestakeModalContent.tsx
  src/components/transactions/StakingMigrate/StakingMigrateActions.tsx
  src/components/transactions/StakingMigrate/StakingMigrateModal.tsx
  src/components/transactions/StakingMigrate/StakingMigrateModalContent.tsx
  src/components/transactions/UnStake/UnStakeActions.tsx
  src/components/transactions/UnStake/UnStakeModalContent.tsx
  src/hooks/stake/common.ts
  src/hooks/stake/useGeneralStakeUiData.ts
  src/hooks/stake/useUserStakeUiData.ts
  src/hooks/useApprovedAmount.tsx
  src/hooks/useModal.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/staking/GetABPTokenModal.tsx
  src/modules/staking/StakingPanel.tsx
  src/modules/staking/StakingPanelNoWallet.tsx
  src/modules/staking/StakingPanelSkeleton.tsx
  src/services/StkAbptMigrationService.ts
  src/ui-config/SharedDependenciesProvider.tsx
  src/ui-config/stakeConfig.ts
  yarn.lock
Labels: QC Passed

#1950 feat: small cleanup and adding search by name and token address on sw…
  src/components/transactions/Switch/SwitchAssetInput.tsx
  src/components/transactions/Switch/SwitchModal.tsx
  src/components/transactions/Switch/SwitchModalContent.tsx
  src/components/transactions/Switch/SwitchTxSuccessView.tsx
  src/ui-config/TokenList.ts
Labels: QC Failed

#1961 fix: link to abpt v1 pool
  pages/staking.staking.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
Labels: QC Passed, Ready for Dev Review

#1860 Feat/React query 5-2, gho hooks
  cypress/e2e/4-gho-ethereum/gho-modal.gho-v3.cy.ts
  package.json
  pages/_app.page.tsx
  src/components/transactions/Borrow/BorrowActions.tsx
  src/components/transactions/Borrow/BorrowModal.tsx
  src/components/transactions/Borrow/GhoBorrowModalContent.tsx
  src/components/transactions/DebtSwitch/DebtSwitchActions.tsx
  src/components/transactions/DebtSwitch/DebtSwitchModalContent.tsx
  src/components/transactions/Repay/RepayActions.tsx
  src/components/transactions/Repay/RepayModalContent.tsx
  src/components/transactions/Supply/SupplyActions.tsx
  src/components/transactions/Swap/SwapModalContent.tsx
  src/components/transactions/Withdraw/WithdrawAndSwitchActions.tsx
  src/helpers/useTransactionHandler.tsx
  src/hooks/app-data-provider/BackgroundDataProvider.tsx
  src/hooks/app-data-provider/useAppDataProvider.tsx
  src/hooks/pool/useGhoPoolFormattedReserve.ts
  src/hooks/pool/useGhoPoolReserve.ts
  src/hooks/pool/useUserGhoPoolFormattedReserve.ts
  src/hooks/pool/useUserGhoPoolReserve.ts
  src/hooks/pool/utils.ts
  src/hooks/useReserveActionState.tsx
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsList.tsx
  src/modules/dashboard/lists/BorrowAssetsList/GhoBorrowAssetsListItem.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListItemWrapper.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/GhoBorrowedPositionsListItem.tsx
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsList.tsx
  src/modules/reserve-overview/ReserveActions.tsx
  src/modules/reserve-overview/ReserveConfigurationWrapper.tsx
  src/modules/reserve-overview/ReserveTopDetailsWrapper.tsx
  src/services/UiGhoService.ts
  src/store/ghoSlice.ts
  src/store/root.ts
  src/ui-config/SharedDependenciesProvider.tsx
  src/ui-config/queries.ts
  src/utils/ghoUtilities.tsx
  yarn.lock
Labels: QC Passed, CI Passed

#1869 feat: sdai wrapping
  package.json
  src/components/infoTooltips/WrappedTokenToolTipContent.tsx
  src/components/transactions/AssetInput.tsx
  src/components/transactions/Supply/SupplyModal.tsx
  src/components/transactions/Supply/SupplyModalContent.tsx
  src/components/transactions/Supply/SupplyWrappedTokenActions.tsx
  src/components/transactions/Withdraw/WithdrawAndSwitchModalContent.tsx
  src/components/transactions/Withdraw/WithdrawAndUnwrapActions.tsx
  src/hooks/token-wrapper/useTokenWrapper.ts
  src/hooks/useApprovedAmount.tsx
  src/hooks/useWrappedTokens.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsList.tsx
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListItem.tsx
  src/services/TokenWrapperService.ts
  src/ui-config/SharedDependenciesProvider.tsx
  src/utils/hfUtils.ts
  yarn.lock
Labels: QC Passed

#1963 feat: add feedback dialog
  src/components/TextWithModal.tsx
  src/components/transactions/FlowCommons/BaseSuccess.tsx
  src/layouts/AppFooter.tsx
  src/layouts/FeedbackDialog.tsx
  src/layouts/MainLayout.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/store/layoutSlice.ts
Labels: QC Passed

#1966 fix: switch feature updates
  src/components/infoTooltips/PriceImpactTooltip.tsx
  src/components/infoTooltips/SlippageTooltip.tsx
  src/components/transactions/DebtSwitch/DebtSwitchActions.tsx
  src/components/transactions/DebtSwitch/DebtSwitchModalContent.tsx
  src/components/transactions/Repay/CollateralRepayActions.tsx
  src/components/transactions/Repay/CollateralRepayModalContent.tsx
  src/components/transactions/Swap/SwapActions.tsx
  src/components/transactions/Swap/SwapModalContent.tsx
  src/components/transactions/Withdraw/WithdrawAndSwitchActions.tsx
  src/components/transactions/Withdraw/WithdrawAndSwitchModalContent.tsx
  src/hooks/paraswap/common.ts
  src/hooks/paraswap/useCollateralRepaySwap.tsx
  src/hooks/paraswap/useCollateralSwap.tsx
  src/hooks/paraswap/useDebtSwitch.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/SlippageList.tsx
Labels: QC Passed
