Repository aave/interface, pull requests merged in 2024-01, with the labels that each got.

#1899 Fix/polygon test coverage
  cypress/e2e/1-v3-markets/3-polygon-v3-market/0-assets/eurs.polygon-v3.cy.ts
  cypress/e2e/1-v3-markets/3-polygon-v3-market/switch.polygon-v3.cy.ts
  cypress/e2e/4-gho-ethereum/helpers/token.helper.ts
Labels: Ready for Dev Review

#1902 feat: add gho config for V3 sepolia test market
  src/modules/markets/Gho/GhoBanner.tsx
  src/ui-config/marketsConfig.tsx
  src/utils/ghoUtilities.tsx
Labels: QC Passed

#1903 fix: remove network icon on list
  src/modules/governance/ProposalV3ListItem.tsx
Labels: QC Passed

#1900 Feat/fork banner
  src/layouts/AppHeader.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
Labels: Ready for Dev Review

#1914 fix: show warning when low FH
  cypress/e2e/4-gho-ethereum/helpers/token.helper.ts
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsList.tsx
Labels: QC Passed, Ready for Dev Review

#1904 feat: add network to voiting info
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/governance/proposal/VoteInfo.tsx
Labels: Ready for Dev Review

#1908 feat: governance subgraph
  pages/governance/v3/proposal/index.governance.tsx
  src/components/transactions/GovVote/GovVoteActions.tsx
  src/components/transactions/GovVote/GovVoteModalContent.tsx
  src/hooks/governance/usePayloadsData.ts
  src/hooks/governance/useProposal.ts
  src/hooks/governance/useProposalVotes.ts
  src/hooks/governance/useProposals.ts
  src/hooks/governance/useProposalsSearch.ts
  src/hooks/useModal.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/governance/ProposalListHeader.tsx
  src/modules/governance/ProposalV3ListItem.tsx
  src/modules/governance/ProposalsV3List.tsx
  src/modules/governance/StateBadge.tsx
  src/modules/governance/proposal/ProposalLifecycle.tsx
  src/modules/governance/proposal/ProposalOverview.tsx
  src/modules/governance/proposal/VoteInfo.tsx
  src/modules/governance/proposal/VotersListContainer.tsx
  src/modules/governance/proposal/VotersListModal.tsx
  src/modules/governance/proposal/VotingResults.tsx
  src/modules/governance/utils/formatProposal.ts
  src/modules/governance/utils/getProposalMetadata.ts
  src/services/VotingMachineService.ts
  src/ui-config/governanceConfig.ts
  src/ui-config/networksConfig.ts
Labels: QC Passed

#1911 feat: bnb [skip cypress]
  public/icons/networks/binance.svg
  public/icons/tokens/bnb.svg
  public/icons/tokens/cake.svg
  public/icons/tokens/wbnb.svg
  src/hooks/paraswap/common.ts
  src/ui-config/marketsConfig.tsx
  src/ui-config/networksConfig.ts
  src/ui-config/reservePatches.ts
Labels: QC Passed

#1917 feat: enable switch features on bnb
  src/ui-config/marketsConfig.tsx
Labels: QC Passed

#1926 feat: add governance-v2-link
  src/modules/governance/GovernanceTopPanel.tsx
Labels: Ready for Dev Review

#1924 feat: add easy access to switch gho
  src/components/transactions/Switch/SwitchModal.tsx
  src/hooks/useModal.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/staking/StakingHeader.tsx
  src/modules/staking/StakingPanel.tsx
Labels: QC Passed

#1921 fix: add in ipfs preview page
  pages/governance/ipfs-preview.governance.tsx
  src/modules/governance/proposal/ProposalOverview.tsx
Labels: QC Passed, Ready for Dev Review
