Repository aave/interface, pull requests merged in 2024-07, with the labels that each got.

#2105 feat: superfest tooltip
  public/icons/other/superfest.svg
  src/components/infoTooltips/SuperFestTooltip.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListItem.tsx
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListMobileItem.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListItem.tsx
  src/modules/dashboard/lists/ListItemWrapper.tsx
  src/modules/dashboard/lists/ListMobileItemWrapper.tsx
  src/utils/utils.ts
Labels: Ready for Dev Review

#2108 feat: add Superfest incentive indicator for weETH supply
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListItem.tsx
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListMobileItem.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListItem.tsx
  src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListItem.tsx
  src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListMobileItem.tsx
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListItem.tsx
  src/modules/markets/MarketAssetsListItem.tsx
  src/modules/markets/MarketAssetsListMobileItem.tsx
  src/utils/utils.ts
Labels: CI Failed

#2127 fix: remove GHO borrow reward - Merit round 7
  src/components/transactions/Borrow/GhoBorrowModalContent.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
  src/modules/dashboard/lists/BorrowAssetsList/GhoBorrowAssetsListItem.tsx
  src/modules/dashboard/lists/BorrowedPositionsList/GhoBorrowedPositionsListItem.tsx
  src/modules/markets/Gho/GhoBanner.tsx
  src/modules/reserve-overview/Gho/GhoDiscountCalculator.tsx
Labels: CI Passed

#2109 feat: implement aave chan interface merit claim page link [skip cypress]
  src/components/incentives/MeritIncentivesTooltipContent.tsx
  src/locales/en/messages.js
  src/locales/en/messages.po
Labels: CI Failed
