Repository aave/interface, pull requests merged in 2024-03, with the labels that each got.

#1863 Feat: React query 5 - 4, pool hooks
  package.json
  pages/_app.page.tsx
  pages/v3-migration.page.tsx
  src/components/transactions/Borrow/BorrowActions.tsx
  src/components/transactions/ClaimRewards/ClaimRewardsActions.tsx
  src/components/transactions/DebtSwitch/DebtSwitchActions.tsx
  src/components/transactions/GovRepresentatives/GovRepresentativesActions.tsx
  src/components/transactions/Repay/RepayActions.tsx
  src/components/transactions/StakingMigrate/StakingMigrateActions.tsx
  src/components/transactions/Supply/SupplyActions.tsx
  src/components/transactions/Supply/SupplyWrappedTokenActions.tsx
  src/components/transactions/Switch/SwitchActions.tsx
  src/components/transactions/Withdraw/WithdrawAndSwitchActions.tsx
  src/components/transactions/Withdraw/WithdrawAndUnwrapActions.tsx
  src/helpers/useGovernanceDelegate.tsx
  src/helpers/useParaSwapTransactionHandler.tsx
  src/helpers/useTransactionHandler.tsx
  src/hooks/app-data-provider/BackgroundDataProvider.tsx
  src/hooks/app-data-provider/useAppDataProvider.tsx
  src/hooks/app-data-provider/useWalletBalances.tsx
  src/hooks/pool/selectors.ts
  src/hooks/pool/useExtendedUserSummaryAndIncentives.ts
  src/hooks/pool/usePoolFormattedReserves.ts
  src/hooks/pool/usePoolReservesIncentives.ts
  src/hooks/pool/useUserPoolReserves.ts
  src/hooks/pool/useUserPoolReservesIncentives.ts
  src/hooks/pool/useUserSummaryAndIncentives.ts
  src/hooks/pool/useUserYield.ts
  src/hooks/useUserReserves.tsx
  src/hooks/useWrappedTokens.tsx
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsList.tsx
  src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListItem.tsx
  src/services/UIPoolService.ts
  src/store/poolSelectors.ts
  src/store/poolSlice.ts
  src/store/root.ts
  src/store/utils/createSingletonSubscriber.ts
  src/ui-config/queries.ts
  src/ui-config/reservePatches.ts
Labels: QC Passed

#1981 fix: asset image in select
  src/components/transactions/Switch/SwitchAssetInput.tsx
Labels: QC Passed

#1823 chore: favicons
  pages/_document.page.tsx
  public/favicon.png
  public/favicon32.ico
  public/favicon32.png
  public/favicon64.png
Labels: QC Passed

#1987 fix: ageur token rename and default image
  public/icons/tokens/eura.svg
  src/components/primitives/TokenIcon.tsx
  src/modules/reserve-overview/ReserveTopDetailsWrapper.tsx
Labels: QC Passed, Ready for Dev Review

#1985 fix: retry MM activation after timeout
  src/libs/web3-data-provider/Web3Provider.tsx
  src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListItem.tsx
Labels: QC Passed

#2001 fix: wrong lens link in footer
  src/layouts/AppFooter.tsx
Labels: CI Failed

#1995 Feat/sepolia markets
  package.json
  src/hooks/useReserveActionState.tsx
  src/locales/en/messages.po
  src/modules/faucet/FaucetAssetsList.tsx
  src/store/protocolDataSlice.ts
  src/ui-config/marketsConfig.tsx
  src/ui-config/networksConfig.ts
  src/utils/utils.ts
  yarn.lock
Labels: QC Passed
